### ISSUE TITLE
Has port 3000 to be reachable by clients or excalidraw only?

### ISSUE THREAD

**Issue by pandel** [NMinhNguyen/excalidraw-json#14]
Hi!

I am trying to create a docker-compose.yml that starts excalidraw, excalidraw-rooms, your rewritten excalidraw-json and minio. ATM, everything starts up, but it seems as if excalidraw isn't able to use anything.

The docker-compose file is providing an overlay network to provide a single network for all containers, but only exposes excalidraw's port to the ouside. Is this wrong? Do normal clients have to have access to your e.-json service directly?

Regards,
Holger

**Comment by NMinhNguyen** [comment]
Hey! I don't think I've actually ever tried running it via Docker, only via PaaS solutions like Vercel or Cloud Foundry, where I'd point at the HTTPS deployment URL. I think that since Excalidraw is using `crypto` stuff in the browser, that only works with HTTPS, so check if you have that set up?

**Comment by pandel** [comment]
Thanks, I'll give it a try! The problem is, that I have to try to get excalidraw up and running without any internet connection at all - it's all about how our internet access is regulated by our datacenter.

I got the local rooms service working without https, so I thought it might work with the storage service also. And additionally, I cannot see anything in excalidraw logs or browser console regarding a connection attempt to the -json service. When should that happen?

**Comment by NMinhNguyen** [comment]
> I got the local rooms service working without https, so I thought it might work with the storage service also. And additionally, I cannot see anything in excalidraw logs or browser console regarding a connection attempt to the -json service. When should that happen?

You can trace where `BACKEND_V2_GET` 
and `BACKEND_V2_POST` are being used: https://github.com/excalidraw/excalidraw/blob/66e5b18e4e3ddf458f94c221edf25f45ca101d6f/src/data/index.ts#L26-L27

**Comment by pandel** [comment]
Thanks! I managed to set up a complete docker-compose.yml with excalidraw, ecalidraw-room, you excalidraw-json, minio and nginx! I am very happy atm that it works. Still have to do some tuning, but cool for now!

Many thanks for your help!
